--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: myappnew
  name: myapp-deployment
spec: 
  replicas: 4
  selector: 
    matchLabels: 
      app: myappnew
  template: 
    metadata: 
      labels: 
        app: myappnew
        env: production
    spec:
      containers:
      - name: myappnew
        image: mycontainerdev.azurecr.io/trial:v1.0.0
        ports:
        - containerPort: 4000
      imagePullSecrets:
      - name: acr-auth
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 4000
  selector:
    app: myappnew